### ISSUE TITLE
Can views and models have configs?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#116]
> ![image](https://cloud.githubusercontent.com/assets/2864371/5202156/d256e9ae-7583-11e4-8484-04e7fde2aef7.png)

If so, how are they supposed to work?

**Comment by ottiker** [comment]
See [here](https://github.com/jillix/engine/blob/master/lib/client/Z.js#L539-L540) and [here](https://github.com/jillix/engine/blob/master/lib/client/Z.js#L581). The configs for a `view` or `model` are just appended to each object. An `instance`, for example, can use this configs for special cases. But I don't know any use case for it and probably the `instance` config is sufficient to handle such cases.

**Comment by ottiker** [comment]
Only on `instances` it makes sense to have a config. Since a `view` or a `model` are standard classes, they don't need custom configurations. Though a module `instance` needs this config to adjust the model itself. An example would be, a paging config for a table `instance`.

Short: Only `instances` can have custom configs.
