### ISSUE TITLE
If model is loaded by an instance, load it on server side as well

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#16]

**Comment by ottiker** [comment]
I guess this issue is about, attaching the model instance on the module instance on the server, when a module is loaded directly from the client.

**Comment by ottiker** [comment]
Since a `model` is cached on the server, it's fast to get the model via the `this._model` factory method.

``` js
// fetch a model
this._model('modelName', function (err, model) {
    // ...
})
```

If we would have the models attached to the `instance` it would require an `if` check, instead of just fetching the model like described above.

``` js
// check if model exists on instance
if (this._models.myModel) {
    // ...
} else {
    this._model('modelName', function (err, model) {
        // ...
    })
}
```

This would complicate things, cause in one case you must provide an `callback` and in the other not.
The difference from the client side is, that the models are generated when an `instance` is loaded and are ready to use inside of the `init` constructor. On the server the `instance` is initialized without `models`.

**Comment by IonicaBizau** [comment]
:+1:
