### ISSUE TITLE
Allow normal npm modules to be loaded as client modules 

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#271]
The client dependencies should support loading normal npm modules. For example, it would be nice to be able to load [`typpy`](https://github.com/IonicaBizau/node-typpy) on the client side, like this:

``` js
var Typpy = require("typpy");
```

...and all these, without a `composition` configuration.

Maybe using Browserify's [`require`](https://github.com/substack/node-browserify#brequirefile-opts) could be a solution. :dizzy: 

Currently, this is a big limitation. On the server side, this is possible, on client it is not.

**Comment by ottiker** [comment]
There are many front-end package managers. We could implement `bower` and would have problems with modules, that have a different package manager. There exists no solution to this problem today. Though there are some standards underway, that could partially solve this problem:
- [WebComponents](http://www.w3.org/wiki/WebComponents/)
- [ES6 Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
- [ES6 Export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)

We could use `clientDependencies` instead of `composition.client.module` to define the client resources. But how do we declare `styles` and `markup` resources? Until there's no standard, we'll have engine compatible and engine incompatible modules.

**Comment by ottiker** [comment]
Here's a good overview of the existing front-end package managers: https://github.com/wilmoore/frontend-packagers

**Comment by IonicaBizau** [comment]
I'm curious how [`electron`](https://github.com/atom/electron)'s `require` works on client side. I tried it some weeks ago and it's actually like the server side, but it's client.

**Comment by IonicaBizau** [comment]
This is probably the biggest limitation I currently have developing Engine apps/modules. Using Browserify doesn't make sense because Engine has its own `require` and minifying things.

Just copying code from other packages and including it in apps/modules would be terrible too.

**Comment by ottiker** [comment]
We need to change engine, so that when a app is installed the modules are packed for front-end use. This way we could support the major front-end package manager like Browserify and Bower. Now engine minifiy compress and combine files all on demand.

**Comment by ottiker** [comment]
The biggest challenge then, would be to standardize the `require` method for the supported front-end package managers.

**Comment by ottiker** [comment]
https://github.com/substack/browserify-handbook#how-browserify-works
