### ISSUE TITLE
What's the recommended way to call server side function from client?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#276]
We tried:
- `self.flow([["flow", "@foo"]])`
- `self.flow([["@foo"]])`
- `self.flow(["@foo"]])`
- `self.flow("@foo")`

---

We should have some examples related to this.

**Comment by ottiker** [comment]
I would say to emit the event `self.flow("@foo")` and have a flow listener config in the `package.json`.

**Comment by IonicaBizau** [comment]
But `self.flow("@foo")` doesn't emit `foo` on server.

**Comment by ottiker** [comment]
True, the '@' must be in the emit call, defined in the `package.json`.
Code: `self.flow("apiEvent");`
Package: `["apiEvent", ["flow", "@foo"]]`

**Comment by IonicaBizau** [comment]
So:
- in the code: `flow("foo")`
- in package.json:
  - client `["foo", "serverEvent"]`
  - server `["serverEvent", "serverMethod"]`

Like this?

**Comment by ottiker** [comment]
Yes, the client package config would have to look like this: `["foo", ["flow", "@serverEvent"]]`, but yeah you got the point :)

**Comment by lcristianiim** [comment]
Related to this issue was the problem from the engine-terminal with the flow configuration.
[Here](https://github.com/jillix/engine-terminal/blob/master/package.json#L40) is the correct flow configuration in package.json provided by adioo.
[And here](https://github.com/jillix/engine-terminal/blob/master/client/index.js#L24) is the correct call.

**Comment by lcristianiim** [comment]
I wanted to close the issue myself but I could not close it.
