### ISSUE TITLE
Make Engine compatible with http

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#306]
...not only https. :thought_balloon:

**Comment by ottiker** [comment]
In the near future everything will be `https` in the internet. What could be a reason why engine should support non secure `http`?

**Comment by IonicaBizau** [comment]
Could be handy if one wants to deploy an Engine app on a server where `https` is not available.

If I'm not wrong, [`spdy`](https://github.com/indutny/node-spdy#usage) supports `http`, so it would be simple to fix this.

**Comment by ottiker** [comment]
I think `spdy` only supports `https`, that's why I also implemented `https`. But I don't think that in the future someone wants to deploy without encryption, given the fact that search engines start to prioritize `https` sites more then unsecure, etc. I think we better find solution to automatically create certificates (ex. letsencrypt), then just implement a _deprecated_ technology.

**Comment by ottiker** [comment]
http://blog.codinghorror.com/should-all-web-traffic-be-encrypted/
