### ISSUE TITLE
What's the best method to use a container inside of <ul>?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/flow-nodejs#50]
`products.html`:

``` html
<ul>
  <li><a href="#">«</a></li>
  <!-- How to render here the other pages? -->
  <li><a href="#">«</a></li>
</ul>
```

`page.html`:

``` html
<li><a href="#">{current}</a></li>
```

The result should be:

``` html
<ul>
  <li><a href="#">«</a></li>
  <li><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#">...</a></li>
  <li><a href="#">n</a></li>
  <li><a href="#">«</a></li>
</ul>
```

Is this possible with the built-in renderer?

**Comment by ottiker** [comment]
Probably there are other solution to this problem.
@IonicaBizau Let us discuss it over a hangout.

**Comment by gabipetrovay** [comment]
... @adioo but post results of the discussion here :)

**Comment by IonicaBizau** [comment]
@gabipetrovay Always. :smile:

**Comment by ottiker** [comment]
It's not possible to use `innerHTML` to "append" HTML between `li` elements. Since the render function uses `innerHTML` we need to find an other ways, which I think are probably a better solution.

There are two workflows to solve this problem:

**1. Alter your data before rendering**
In this use case we want to append a left and right button to the pagination list. That can be easily done by altering the data before rendering.

``` js
var data = [{pageNr: 1}, {pageNr: 2}, {pageNr: 3}];
data.unshift({pageNr: '<<'});
data.push({pageNr: '>>'});
// data is now [{pageNr: '<<'}, {pageNr: 1}, {pageNr: 2}, {pageNr: 3}, {pageNr: '>>'}]
```

After adjusting the data, we can just pass it to the render function `self.view.paging.render(data)`.

**2. Use the `on.html` handler function**
Assuming we have super special left and right buttons, we can change the html string before it's appended to the DOM with the `innerHTML` method.

``` html
<ul>
    <li><button><i class="specal-icon-left"></i></button></li>
    [myCustomReplaceIdentifier]
    <li><button><i class="specal-icon-right"></i></button></li>
<ul>
```

Now, the module generates the HTML string for the `li` pagination elements. And uses the `on.html` handler, to replace the HTML before it's appended to the DOM.

``` js
self.view.paging.on.html = function (html) {
    // do replacing
    return html;
}
self.view.paging.render();
```

Note: Solution nr. 1 can also render HTML inside of the data object: `[{pageNr: '<button><i class="specal-icon-right"></i></button>'}]`. For that we need to disable the escaping in the render function, which will be possible after issue #21 is merged.

**Comment by ottiker** [comment]
@IonicaBizau You can close the issue, when you successfully implemented one of the above solutions.

**Comment by IonicaBizau** [comment]
I [chose](https://github.com/IonicaBizau/engine-list/commit/f457261f21ebfd732e5e777b5bbf4fb5904497c4) the second workflow since we maybe need custom HTML for right and left buttons.
